#!/usr/bin/env node
/**
 * Regenerate the app's ABI modules from the contracts repo.
 *
 *   node packages/contracts/scripts/gen-abis.mjs
 *
 * Source of truth is Berth-Club/launchpad-contracts-v2/abi/*.json, fetched with
 * `gh api` because the repo is private. Nothing here is hand-editable: an ABI
 * that has drifted from the deployed contract changes topic0, and ponder then
 * matches ZERO logs and raises no error — indistinguishable from "nobody has
 * launched yet". Regenerate after every contracts deployment.
 *
 * Writes:
 *   apps/web/lib/abis/*.ts      full ABIs the app calls
 *   apps/indexer/abis/berth.ts  event-only ABIs the indexer filters on
 */
import { execFileSync } from "node:child_process"
import { mkdirSync, writeFileSync } from "node:fs"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"

const REPO = "Berth-Club/launchpad-contracts-v2"
const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../../..")

/** contract name -> exported const name. */
const WEB = {
  BerthClubLaunchFactory: "LaunchFactoryAbi",
  BerthClubMultiLaunchFactory: "MultiLaunchFactoryAbi",
  BerthClubRouter: "RouterAbi",
  BerthClubMultiRouter: "MultiRouterAbi",
  BerthClubLaunchLocker: "LaunchLockerAbi",
  BerthClubFeeEscrow: "FeeEscrowAbi",
  BerthClubQuotePricer: "QuotePricerAbi",
  BerthClubLauncherToken: "LauncherTokenAbi",
}

/**
 * The indexer gets FULL ABIs, not events-only.
 *
 * It filters logs by event, but its handlers also `readContract` against the
 * token and the factory — identity and economics are not in v2's TokenLaunched.
 * An events-only bundle typechecks against ponder's loose signatures and then
 * throws `AbiFunctionNotFoundError` on the first real launch, which is exactly
 * the failure this generator exists to prevent.
 */
const INDEXER = {
  BerthClubLaunchFactory: "LaunchFactoryAbi",
  BerthClubMultiLaunchFactory: "MultiLaunchFactoryAbi",
  BerthClubLaunchLocker: "LaunchLockerAbi",
  BerthClubLauncherToken: "LauncherTokenAbi",
}

function fetchAbi(name) {
  const b64 = execFileSync(
    "gh",
    ["api", `repos/${REPO}/contents/abi/${name}.json`, "--jq", ".content"],
    { encoding: "utf8", maxBuffer: 32 * 1024 * 1024 },
  )
  return JSON.parse(Buffer.from(b64, "base64").toString("utf8"))
}

function header(source) {
  return `// AUTO-GENERATED by packages/contracts/scripts/gen-abis.mjs.
// Source of truth: ${source} (github.com/${REPO}).
// Do not hand-edit — regenerate. A stale ABI changes topic0 and the indexer
// then matches zero logs with no error.
`
}

const abis = {}
for (const name of new Set([...Object.keys(WEB), ...Object.keys(INDEXER)])) {
  abis[name] = fetchAbi(name)
  process.stderr.write(`fetched ${name} (${abis[name].length} entries)\n`)
}

// one module per contract for the app
const webDir = resolve(ROOT, "apps/web/lib/abis")
mkdirSync(webDir, { recursive: true })
const index = []
for (const [name, exported] of Object.entries(WEB)) {
  const file = exported.replace(/Abi$/, "").replace(/^./, (c) => c.toLowerCase())
  writeFileSync(
    resolve(webDir, `${file}.ts`),
    `${header(`abi/${name}.json`)}\nexport const ${exported} = ${JSON.stringify(abis[name], null, 2)} as const\n`,
  )
  index.push(`export { ${exported} } from "./${file}"`)
}
writeFileSync(resolve(webDir, "index.ts"), `${header("abi/*.json")}\n${index.join("\n")}\n`)

const bundle = Object.entries(INDEXER)
  .map(
    ([name, exported]) =>
      `export const ${exported} = ${JSON.stringify(abis[name], null, 2)} as const`,
  )
  .join("\n\n")
mkdirSync(resolve(ROOT, "apps/indexer/abis"), { recursive: true })
writeFileSync(resolve(ROOT, "apps/indexer/abis/berth.ts"), `${header("abi/*.json")}\n${bundle}\n`)

process.stderr.write("wrote apps/web/lib/abis/* and apps/indexer/abis/berth.ts\n")
