// AUTO-GENERATED by packages/contracts/scripts/gen-abis.mjs.
// Source of truth: abi/BerthClubMultiRouter.json (github.com/Berth-Club/launchpad-contracts-v2).
// Do not hand-edit — regenerate. A stale ABI changes topic0 and the indexer
// then matches zero logs with no error.

export const MultiRouterAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "manager_",
        "type": "address",
        "internalType": "contract IPoolManager"
      },
      {
        "name": "factory_",
        "type": "address",
        "internalType": "contract BerthClubMultiLaunchFactory"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "receive",
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "buyWithNative",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "legs",
        "type": "tuple[]",
        "internalType": "struct BerthClubMultiRouter.Leg[]",
        "components": [
          {
            "name": "market",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "hops",
            "type": "tuple[]",
            "internalType": "struct Hop[]",
            "components": [
              {
                "name": "key",
                "type": "tuple",
                "internalType": "struct PoolKey",
                "components": [
                  {
                    "name": "currency0",
                    "type": "address",
                    "internalType": "Currency"
                  },
                  {
                    "name": "currency1",
                    "type": "address",
                    "internalType": "Currency"
                  },
                  {
                    "name": "fee",
                    "type": "uint24",
                    "internalType": "uint24"
                  },
                  {
                    "name": "tickSpacing",
                    "type": "int24",
                    "internalType": "int24"
                  },
                  {
                    "name": "hooks",
                    "type": "address",
                    "internalType": "contract IHooks"
                  }
                ]
              }
            ]
          },
          {
            "name": "amountIn",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      },
      {
        "name": "minTokensOut",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "recipient",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "tokensOut",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "buyWithQuote",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "market",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "quoteIn",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "minTokensOut",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "recipient",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "tokensOut",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "factory",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract BerthClubMultiLaunchFactory"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "launchAndBuyWithNative",
    "inputs": [
      {
        "name": "params",
        "type": "tuple",
        "internalType": "struct BerthClubMultiLaunchFactory.TokenParams",
        "components": [
          {
            "name": "name",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "symbol",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "logo",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "description",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "socials",
            "type": "tuple",
            "internalType": "struct BerthClubLauncherToken.Socials",
            "components": [
              {
                "name": "twitter",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "telegram",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "discord",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "website",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "farcaster",
                "type": "string",
                "internalType": "string"
              }
            ]
          },
          {
            "name": "creatorFeeRecipient",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "creatorTaxBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "expectedEconomics",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "salt",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      },
      {
        "name": "launchConfigId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "pairTokens",
        "type": "address[]",
        "internalType": "address[]"
      },
      {
        "name": "legs",
        "type": "tuple[]",
        "internalType": "struct BerthClubMultiRouter.Leg[]",
        "components": [
          {
            "name": "market",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "hops",
            "type": "tuple[]",
            "internalType": "struct Hop[]",
            "components": [
              {
                "name": "key",
                "type": "tuple",
                "internalType": "struct PoolKey",
                "components": [
                  {
                    "name": "currency0",
                    "type": "address",
                    "internalType": "Currency"
                  },
                  {
                    "name": "currency1",
                    "type": "address",
                    "internalType": "Currency"
                  },
                  {
                    "name": "fee",
                    "type": "uint24",
                    "internalType": "uint24"
                  },
                  {
                    "name": "tickSpacing",
                    "type": "int24",
                    "internalType": "int24"
                  },
                  {
                    "name": "hooks",
                    "type": "address",
                    "internalType": "contract IHooks"
                  }
                ]
              }
            ]
          },
          {
            "name": "amountIn",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      },
      {
        "name": "minTokensOut",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "tokensOut",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "manager",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IPoolManager"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "sellToNative",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "legs",
        "type": "tuple[]",
        "internalType": "struct BerthClubMultiRouter.Leg[]",
        "components": [
          {
            "name": "market",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "hops",
            "type": "tuple[]",
            "internalType": "struct Hop[]",
            "components": [
              {
                "name": "key",
                "type": "tuple",
                "internalType": "struct PoolKey",
                "components": [
                  {
                    "name": "currency0",
                    "type": "address",
                    "internalType": "Currency"
                  },
                  {
                    "name": "currency1",
                    "type": "address",
                    "internalType": "Currency"
                  },
                  {
                    "name": "fee",
                    "type": "uint24",
                    "internalType": "uint24"
                  },
                  {
                    "name": "tickSpacing",
                    "type": "int24",
                    "internalType": "int24"
                  },
                  {
                    "name": "hooks",
                    "type": "address",
                    "internalType": "contract IHooks"
                  }
                ]
              }
            ]
          },
          {
            "name": "amountIn",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      },
      {
        "name": "minNativeOut",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "recipient",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "nativeOut",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "sellToQuotes",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "legs",
        "type": "tuple[]",
        "internalType": "struct BerthClubMultiRouter.Leg[]",
        "components": [
          {
            "name": "market",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "hops",
            "type": "tuple[]",
            "internalType": "struct Hop[]",
            "components": [
              {
                "name": "key",
                "type": "tuple",
                "internalType": "struct PoolKey",
                "components": [
                  {
                    "name": "currency0",
                    "type": "address",
                    "internalType": "Currency"
                  },
                  {
                    "name": "currency1",
                    "type": "address",
                    "internalType": "Currency"
                  },
                  {
                    "name": "fee",
                    "type": "uint24",
                    "internalType": "uint24"
                  },
                  {
                    "name": "tickSpacing",
                    "type": "int24",
                    "internalType": "int24"
                  },
                  {
                    "name": "hooks",
                    "type": "address",
                    "internalType": "contract IHooks"
                  }
                ]
              }
            ]
          },
          {
            "name": "amountIn",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      },
      {
        "name": "minOuts",
        "type": "uint256[]",
        "internalType": "uint256[]"
      },
      {
        "name": "recipient",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "unlockCallback",
    "inputs": [
      {
        "name": "raw",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "MultiBuy",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "buyer",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "nativeIn",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "tokensOut",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "legs",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "MultiSell",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "seller",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "tokensIn",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "nativeOut",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "legs",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "MultiSellToQuotes",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "seller",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "tokensIn",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "legs",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "InsufficientLaunchValue",
    "inputs": []
  },
  {
    "type": "error",
    "name": "LegMustEndAtQuote",
    "inputs": []
  },
  {
    "type": "error",
    "name": "LengthMismatch",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NativeAliasNotAllowed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NativeTransferFailed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NativeValueMismatch",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NoLegs",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotPoolManager",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ReentrancyGuardReentrantCall",
    "inputs": []
  },
  {
    "type": "error",
    "name": "RouteBroken",
    "inputs": [
      {
        "name": "index",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "RouteEndMismatch",
    "inputs": [
      {
        "name": "expected",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "actual",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "SafeCastOverflowedUintToInt",
    "inputs": [
      {
        "name": "value",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "SafeERC20FailedOperation",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "SlippageExceeded",
    "inputs": [
      {
        "name": "amountOut",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "minAmountOut",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "ZeroAddress",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroAmount",
    "inputs": []
  }
] as const
